services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sveltePotato42!
      POSTGRES_DB: svelte-learns
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
